import Fastify, { FastifyReply, FastifyRequest } from 'fastify';
import cookie from '@fastify/cookie'; import rateLimit from '@fastify/rate-limit'; import argon2 from 'argon2';
import { and, eq, gt, isNull, sql } from 'drizzle-orm'; import { NodePgDatabase } from 'drizzle-orm/node-postgres'; import { createHash, randomBytes, timingSafeEqual } from 'node:crypto'; import { z } from 'zod';
import * as s from './schema.js'; import { Config } from './config.js';

export interface TokenMailer { sendVerification(email:string,token:string):Promise<void>; sendPasswordReset(email:string,token:string):Promise<void> }
export const silentMailer:TokenMailer={async sendVerification(){},async sendPasswordReset(){}};
const hash=(v:string)=>createHash('sha256').update(v).digest('hex'); const token=()=>randomBytes(32).toString('base64url');
const passwordOptions={type:argon2.argon2id,memoryCost:19456,timeCost:2,parallelism:1} as const;
const credentials=z.object({email:z.string().email().max(320).transform(v=>v.trim().toLowerCase()),password:z.string().min(12).max(200)});
const publicUser=(u:typeof s.users.$inferSelect)=>({id:u.id,email:u.email,displayName:u.displayName,emailVerified:u.emailVerified,createdAt:u.createdAt});

export function buildApp(db:NodePgDatabase<typeof s>,cfg:Config,mailer:TokenMailer=silentMailer){
 const app=Fastify({logger:false,trustProxy:true}); app.register(cookie,{secret:cfg.COOKIE_SECRET}); app.register(rateLimit,{global:false});
 app.setErrorHandler((e,_q,r)=>{ if(e instanceof z.ZodError)return r.status(400).send({error:{code:'VALIDATION_ERROR',details:e.issues.map(i=>({path:i.path.join('.'),message:i.message}))}}); const status=(e as any).statusCode||500; return r.status(status).send({error:{code:status===429?'RATE_LIMITED':'INTERNAL_ERROR'}}); });
 const cookieOpts={httpOnly:true,sameSite:'strict' as const,secure:cfg.NODE_ENV==='production',path:'/'};
 async function issue(userId:string,r:FastifyReply){const raw=token(),csrf=token(),expiresAt=new Date(Date.now()+cfg.SESSION_TTL_HOURS*3600000); await db.insert(s.sessions).values({idHash:hash(raw),userId,csrfHash:hash(csrf),expiresAt}); r.setCookie('session',raw,{...cookieOpts,expires:expiresAt}).setCookie('csrf',csrf,{...cookieOpts,httpOnly:false,expires:expiresAt});}
 async function auth(q:FastifyRequest,r:FastifyReply){const raw=q.cookies.session;if(!raw)return r.status(401).send({error:{code:'AUTH_REQUIRED'}});const rows=await db.select({session:s.sessions,user:s.users}).from(s.sessions).innerJoin(s.users,eq(s.sessions.userId,s.users.id)).where(and(eq(s.sessions.idHash,hash(raw)),gt(s.sessions.expiresAt,new Date()))).limit(1);if(!rows[0]){r.clearCookie('session',{path:'/'});return r.status(401).send({error:{code:'AUTH_REQUIRED'}})};(q as any).account=rows[0];}
 async function csrf(q:FastifyRequest,r:FastifyReply){const a=(q as any).account;if(!a)return;const provided=q.headers['x-csrf-token'];if(typeof provided!=='string'||provided.length<20||!timingSafeEqual(Buffer.from(hash(provided)),Buffer.from(a.session.csrfHash)))return r.status(403).send({error:{code:'CSRF_INVALID'}});}
 const protectedMutation={preHandler:[auth,csrf]};
 app.post('/v1/auth/register',async(q,r)=>{const body=credentials.parse(q.body);const passwordHash=await argon2.hash(body.password,passwordOptions);try{const [u]=await db.transaction(async tx=>{const us=await tx.insert(s.users).values({email:body.email,passwordHash}).returning();await tx.insert(s.accountUsage).values({userId:us[0].id,wordAllowance:cfg.DEFAULT_WORD_ALLOWANCE});return us});const verify=token();await db.insert(s.passwordResets).values({tokenHash:hash(verify),userId:u.id,purpose:'verify',expiresAt:new Date(Date.now()+cfg.TOKEN_TTL_MINUTES*60000)});await mailer.sendVerification(u.email,verify);await issue(u.id,r);return r.status(201).send({user:publicUser(u)});}catch(e:any){if(e?.code==='23505')return r.status(409).send({error:{code:'EMAIL_IN_USE'}});throw e;}});
 app.post('/v1/auth/login',{config:{rateLimit:{max:5,timeWindow:'1 minute'}}},async(q,r)=>{const body=credentials.parse(q.body);const [u]=await db.select().from(s.users).where(eq(s.users.email,body.email)).limit(1);const ok=u?await argon2.verify(u.passwordHash,body.password):false;if(!u||!ok)return r.status(401).send({error:{code:'INVALID_CREDENTIALS'}});await issue(u.id,r);await db.insert(s.auditEvents).values({userId:u.id,event:'login',ip:q.ip});return {user:publicUser(u)};});
 app.post('/v1/auth/logout',protectedMutation,async(q,r)=>{await db.delete(s.sessions).where(eq(s.sessions.idHash,hash(q.cookies.session!)));return r.clearCookie('session',{path:'/'}).clearCookie('csrf',{path:'/'}).status(204).send();});
 app.get('/v1/auth/session',{preHandler:auth},async(q)=>({user:publicUser((q as any).account.user)}));
 app.post('/v1/auth/verify',async(q,r)=>{const b=z.object({token:z.string().min(20)}).parse(q.body);const used=await db.update(s.passwordResets).set({usedAt:new Date()}).where(and(eq(s.passwordResets.tokenHash,hash(b.token)),eq(s.passwordResets.purpose,'verify'),isNull(s.passwordResets.usedAt),gt(s.passwordResets.expiresAt,new Date()))).returning();if(!used[0])return r.status(400).send({error:{code:'TOKEN_INVALID'}});await db.update(s.users).set({emailVerified:true,updatedAt:new Date()}).where(eq(s.users.id,used[0].userId));return {ok:true};});
 app.post('/v1/auth/password-reset/request',{config:{rateLimit:{max:3,timeWindow:'15 minutes'}}},async(q)=>{const {email}=z.object({email:z.string().email().transform(v=>v.trim().toLowerCase())}).parse(q.body);const [u]=await db.select().from(s.users).where(eq(s.users.email,email)).limit(1);if(u){const raw=token();await db.insert(s.passwordResets).values({tokenHash:hash(raw),userId:u.id,purpose:'reset',expiresAt:new Date(Date.now()+cfg.TOKEN_TTL_MINUTES*60000)});await mailer.sendPasswordReset(email,raw)}return {ok:true};});
 app.post('/v1/auth/password-reset/complete',async(q,r)=>{const b=z.object({token:z.string().min(20),password:z.string().min(12).max(200)}).parse(q.body);const result=await db.transaction(async tx=>{const rows=await tx.update(s.passwordResets).set({usedAt:new Date()}).where(and(eq(s.passwordResets.tokenHash,hash(b.token)),eq(s.passwordResets.purpose,'reset'),isNull(s.passwordResets.usedAt),gt(s.passwordResets.expiresAt,new Date()))).returning();if(!rows[0])return false;await tx.update(s.users).set({passwordHash:await argon2.hash(b.password,passwordOptions),updatedAt:new Date()}).where(eq(s.users.id,rows[0].userId));await tx.delete(s.sessions).where(eq(s.sessions.userId,rows[0].userId));return true});return result?{ok:true}:r.status(400).send({error:{code:'TOKEN_INVALID'}});});
 app.get('/v1/account',{preHandler:auth},async(q)=>({user:publicUser((q as any).account.user)}));
 app.patch('/v1/account',protectedMutation,async(q)=>{const {displayName}=z.object({displayName:z.string().trim().min(1).max(100).nullable()}).parse(q.body);const [u]=await db.update(s.users).set({displayName,updatedAt:new Date()}).where(eq(s.users.id,(q as any).account.user.id)).returning();return {user:publicUser(u)};});
 app.post('/v1/account/password',protectedMutation,async(q,r)=>{const b=z.object({currentPassword:z.string(),newPassword:z.string().min(12).max(200)}).parse(q.body),u=(q as any).account.user;if(!await argon2.verify(u.passwordHash,b.currentPassword))return r.status(401).send({error:{code:'INVALID_CREDENTIALS'}});await db.update(s.users).set({passwordHash:await argon2.hash(b.newPassword,passwordOptions),updatedAt:new Date()}).where(eq(s.users.id,u.id));await db.delete(s.sessions).where(and(eq(s.sessions.userId,u.id),sql`${s.sessions.idHash} <> ${hash(q.cookies.session!)}`));return {ok:true};});
 app.delete('/v1/account',protectedMutation,async(q,r)=>{await db.delete(s.users).where(eq(s.users.id,(q as any).account.user.id));return r.clearCookie('session',{path:'/'}).clearCookie('csrf',{path:'/'}).status(204).send();});
 app.post('/v1/documents',protectedMutation,async(q,r)=>{const b=z.object({title:z.string().min(1).max(200),content:z.string().max(2_000_000)}).parse(q.body),uid=(q as any).account.user.id;const words=b.content.trim()?b.content.trim().split(/\s+/u).length:0;const result=await db.transaction(async tx=>{const usage=await tx.update(s.accountUsage).set({wordsUsed:sql`${s.accountUsage.wordsUsed} + ${words}`,updatedAt:new Date()}).where(and(eq(s.accountUsage.userId,uid),sql`${s.accountUsage.wordsUsed} + ${words} <= ${s.accountUsage.wordAllowance}`)).returning();if(!usage[0])return null;return (await tx.insert(s.documents).values({userId:uid,title:b.title,content:b.content,wordCount:words}).returning())[0]});return result?r.status(201).send({document:result}):r.status(403).send({error:{code:'WORD_ALLOWANCE_EXCEEDED'}});});
 app.get('/v1/documents/:id',{preHandler:auth},async(q,r)=>{const {id}=z.object({id:z.string().uuid()}).parse(q.params),uid=(q as any).account.user.id;const [doc]=await db.select().from(s.documents).where(and(eq(s.documents.id,id),eq(s.documents.userId,uid))).limit(1);return doc?{document:doc}:r.status(404).send({error:{code:'DOCUMENT_NOT_FOUND'}});});
 return app;
}
