import { and, desc, eq, isNull, sql } from 'drizzle-orm';
import { NodePgDatabase } from 'drizzle-orm/node-postgres';
import * as s from './schema.js';

const workflowStatuses = ['draft','processing','review','complete','failed'] as const;
const iso = (value: Date | string | null) => value == null ? null : new Date(value).toISOString();

export function utcBillingPeriod(now = new Date()) { return {start:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)),end:new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()+1,1))}; }
export async function getUsage(db:NodePgDatabase<typeof s>,userId:string) { const [row]=await db.select().from(s.accountUsage).where(eq(s.accountUsage.userId,userId)).limit(1); if(!row)return {wordsProcessed:0,wordAllowance:0,remainingWords:0,periodStart:null,periodEnd:null}; if(row.periodEnd<=new Date()){const period=utcBillingPeriod();return {wordsProcessed:0,wordAllowance:row.wordAllowance,remainingWords:row.wordAllowance,periodStart:iso(period.start),periodEnd:iso(period.end)}} return {wordsProcessed:row.wordsUsed,wordAllowance:row.wordAllowance,remainingWords:Math.max(0,row.wordAllowance-row.wordsUsed),periodStart:iso(row.periodStart),periodEnd:iso(row.periodEnd)}; }
export async function getDocumentTotals(db:NodePgDatabase<typeof s>,userId:string) { const rows=await db.select({status:s.documents.workflowStatus,total:sql<number>`count(*)::int`}).from(s.documents).where(eq(s.documents.userId,userId)).groupBy(s.documents.workflowStatus); const byStatus=Object.fromEntries(workflowStatuses.map(status=>[status,0])) as Record<(typeof workflowStatuses)[number],number>; for(const row of rows)if(row.status in byStatus)byStatus[row.status as keyof typeof byStatus]=row.total; return {total:Object.values(byStatus).reduce((sum,value)=>sum+value,0),byStatus}; }
export async function getProtectedDetailTotal(db:NodePgDatabase<typeof s>,userId:string) { const [row]=await db.select({total:sql<number>`coalesce(sum(${s.documents.protectedDetailCount}),0)::int`}).from(s.documents).where(eq(s.documents.userId,userId)); return {total:row?.total??0}; }
export async function getOutstandingWarnings(db:NodePgDatabase<typeof s>,userId:string) { const [row]=await db.select({total:sql<number>`count(*)::int`}).from(s.reviewWarnings).where(and(eq(s.reviewWarnings.userId,userId),isNull(s.reviewWarnings.resolvedAt))); return {total:row?.total??0}; }
export async function getRecentDocuments(db:NodePgDatabase<typeof s>,userId:string,limit=5) { const rows=await db.select({id:s.documents.id,title:s.documents.title,wordCount:s.documents.wordCount,status:s.documents.workflowStatus,updatedAt:s.documents.updatedAt}).from(s.documents).where(eq(s.documents.userId,userId)).orderBy(desc(s.documents.updatedAt)).limit(limit); return {documents:rows.map(row=>({...row,updatedAt:iso(row.updatedAt)!}))}; }
export async function getNotifications(db:NodePgDatabase<typeof s>,userId:string,limit=20) { const [rows,countRows]=await Promise.all([db.select().from(s.notifications).where(eq(s.notifications.userId,userId)).orderBy(desc(s.notifications.createdAt)).limit(limit),db.select({total:sql<number>`count(*)::int`}).from(s.notifications).where(and(eq(s.notifications.userId,userId),isNull(s.notifications.readAt)))]); return {notifications:rows.map(row=>({id:row.id,title:row.title,body:row.body,isRead:row.readAt!==null,readAt:iso(row.readAt),createdAt:iso(row.createdAt)!})),unreadCount:countRows[0]?.total??0}; }
export async function getUsageHistory(db:NodePgDatabase<typeof s>,userId:string,months=12) { const rows=await db.select({month:s.usageHistory.monthStart,wordsProcessed:s.usageHistory.wordsProcessed}).from(s.usageHistory).where(eq(s.usageHistory.userId,userId)).orderBy(desc(s.usageHistory.monthStart)).limit(months); return {months:rows.reverse().map(row=>({month:iso(row.month)!,wordsProcessed:row.wordsProcessed}))}; }
export async function getSubscription(db:NodePgDatabase<typeof s>,userId:string) { const [row]=await db.select().from(s.subscriptions).where(eq(s.subscriptions.userId,userId)).limit(1); return row?{planCode:row.planCode,planName:row.planName,wordAllowance:row.wordAllowance,renewsAt:iso(row.renewalAt),billingEnabled:false}:{planCode:'free',planName:'Free',wordAllowance:0,renewsAt:null,billingEnabled:false}; }
export async function getDashboard(db:NodePgDatabase<typeof s>,userId:string) { const [usage,documents,protectedDetails,reviewWarnings,recentDocuments,notifications,usageHistory,subscription]=await Promise.all([getUsage(db,userId),getDocumentTotals(db,userId),getProtectedDetailTotal(db,userId),getOutstandingWarnings(db,userId),getRecentDocuments(db,userId),getNotifications(db,userId),getUsageHistory(db,userId),getSubscription(db,userId)]); return {usage,documents,protectedDetails,reviewWarnings,recentDocuments,notifications,usageHistory,subscription}; }
