import { bigint, boolean, index, integer, jsonb, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

export const users = pgTable('users', { id: uuid('id').primaryKey().defaultRandom(), email: text('email').notNull(), passwordHash: text('password_hash').notNull(), displayName: text('display_name'), emailVerified: boolean('email_verified').notNull().default(false), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow() }, t => [uniqueIndex('users_email_uq').on(t.email)]);
export const sessions = pgTable('sessions', { idHash: text('id_hash').primaryKey(), userId: uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), csrfHash: text('csrf_hash').notNull(), expiresAt: timestamp('expires_at',{withTimezone:true}).notNull(), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow() }, t => [index('sessions_user_idx').on(t.userId)]);
export const passwordResets = pgTable('password_resets', { tokenHash: text('token_hash').primaryKey(), userId: uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), purpose: text('purpose').notNull(), expiresAt: timestamp('expires_at',{withTimezone:true}).notNull(), usedAt: timestamp('used_at',{withTimezone:true}), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow() });
export const documents = pgTable('documents', { id: uuid('id').primaryKey().defaultRandom(), userId: uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), title: text('title').notNull(), wordCount: integer('word_count').notNull(), content: text('content').notNull(), workflowStatus: text('workflow_status').notNull().default('draft'), protectedDetailCount: integer('protected_detail_count').notNull().default(0), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow() }, t => [index('documents_owner_idx').on(t.userId),index('documents_owner_updated_idx').on(t.userId,t.updatedAt)]);
export const accountUsage = pgTable('account_usage', { userId: uuid('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}), wordsUsed: bigint('words_used',{mode:'number'}).notNull().default(0), wordAllowance: bigint('word_allowance',{mode:'number'}).notNull(), periodStart: timestamp('period_start',{withTimezone:true}).notNull(), periodEnd: timestamp('period_end',{withTimezone:true}).notNull(), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow() });
export const usageHistory = pgTable('usage_history', { userId: uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), monthStart: timestamp('month_start',{withTimezone:true}).notNull(), wordsProcessed: bigint('words_processed',{mode:'number'}).notNull().default(0) }, t => [uniqueIndex('usage_history_user_month_uq').on(t.userId,t.monthStart)]);
export const reviewWarnings = pgTable('review_warnings', { id: uuid('id').primaryKey().defaultRandom(), userId: uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), documentId: uuid('document_id').references(()=>documents.id,{onDelete:'cascade'}), message: text('message').notNull(), resolvedAt: timestamp('resolved_at',{withTimezone:true}), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow() }, t => [index('review_warnings_owner_idx').on(t.userId)]);
export const notifications = pgTable('notifications', { id: uuid('id').primaryKey().defaultRandom(), userId: uuid('user_id').notNull().references(()=>users.id,{onDelete:'cascade'}), title: text('title').notNull(), body: text('body').notNull(), readAt: timestamp('read_at',{withTimezone:true}), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow() }, t => [index('notifications_owner_created_idx').on(t.userId,t.createdAt)]);
export const subscriptions = pgTable('subscriptions', { userId: uuid('user_id').primaryKey().references(()=>users.id,{onDelete:'cascade'}), planCode: text('plan_code').notNull().default('free'), planName: text('plan_name').notNull().default('Free'), wordAllowance: bigint('word_allowance',{mode:'number'}).notNull().default(0), renewalAt: timestamp('renewal_at',{withTimezone:true}), provider: text('provider'), providerSubscriptionId: text('provider_subscription_id'), updatedAt: timestamp('updated_at',{withTimezone:true}).notNull().defaultNow() });
export const auditEvents = pgTable('audit_events', { id: uuid('id').primaryKey().defaultRandom(), userId: uuid('user_id').references(()=>users.id,{onDelete:'set null'}), event: text('event').notNull(), ip: text('ip'), metadata: jsonb('metadata').notNull().default({}), createdAt: timestamp('created_at',{withTimezone:true}).notNull().defaultNow() }, t => [index('audit_user_idx').on(t.userId)]);
