import { useEffect, useState } from 'react'
import { ArrowRight, Check, ChevronRight, Clock3, FileText, PenLine, RefreshCcw, Sparkles, TrendingUp } from 'lucide-react'
import { Link } from 'react-router-dom'
import { api, DashboardData, ProcessingJob } from '../lib/api'

function LoadingCards() { return <div className="metric-grid" aria-label="Loading dashboard" aria-busy="true">{[1,2,3].map(i => <div className="card metric skeleton-card" key={i}><span/><span/><span/></div>)}</div> }

export function Dashboard() {
  const [data, setData] = useState<DashboardData | null>(null)
  const [error, setError] = useState('')
  const [retry, setRetry] = useState(0)
  const [jobs, setJobs] = useState<ProcessingJob[]>([])
  useEffect(() => { let active = true; setError(''); api.dashboard().then(result => { if (active) setData(result) }).catch(() => { if (active) setError('We couldn’t load your workspace data.') }); return () => { active = false } }, [retry])
  useEffect(() => { let active=true; const refresh=()=>api.jobs().then(v=>{if(active)setJobs(v.jobs)}).catch(()=>{});refresh();const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer)}},[retry])
  return <div className="dashboard">
    <section className="welcome"><div><p className="eyebrow">Friday, August 7</p><h2>Good morning, Alex.</h2><p>Here’s what’s happening with your writing workspace.</p></div><Link className="button primary desktop-cta" to="/app/rewrite"><PenLine size={17}/>Start a rewrite</Link></section>
    {error ? <div className="error-state" role="alert"><div><strong>Something went wrong</strong><p>{error} Check your connection and try again.</p></div><button className="button secondary" onClick={() => setRetry(v => v+1)}><RefreshCcw size={16}/>Try again</button></div> : !data ? <LoadingCards/> : data.metrics.length === 0 ? <div className="empty-state card"><FileText/><h3>No activity yet</h3><p>Your writing metrics will appear after your first rewrite.</p><Link to="/app/rewrite" className="text-link">Create your first rewrite <ArrowRight size={15}/></Link></div> : <div className="metric-grid">{data.metrics.slice(0,3).map((m,i) => <article className="card metric" key={m.label}><div className={`metric-icon tone-${i}`}><span>{i === 0 ? <Sparkles/> : i === 1 ? <FileText/> : <TrendingUp/>}</span></div><p>{m.label}</p><div><strong>{typeof m.value === 'number' ? m.value.toLocaleString() : m.value}</strong>{m.change && <span className="positive">{m.change}</span>}</div><small>{i === 0 ? 'Across all documents' : i === 1 ? 'This billing period' : 'Compared with last month'}</small></article>)}</div>}
    <section className="rewrite-banner"><div className="rewrite-art" aria-hidden="true"><span className="paper paper-back"/><span className="paper"><i/><i/><i/></span><Sparkles/></div><div><span className="pill">AI-powered rewriting</span><h2>Make every word sound like you.</h2><p>Transform AI-generated text into clear, natural writing while keeping your original meaning intact.</p></div><Link className="button light" to="/app/rewrite">New rewrite <ArrowRight size={17}/></Link></section>
    {jobs.length>0&&<section className="card jobs-panel"><div className="panel-head"><div><p className="eyebrow">Processing queue</p><h3>Recent jobs</h3></div></div>{jobs.slice(0,5).map(job=><div className="job-row" key={job.id}><div><strong>{job.operation.replaceAll('_',' ')}</strong><span>{job.state==='processing'?`${job.progress}% complete`:job.state==='queued'?'Waiting for a worker':job.state==='failed'?(job.errorMessage??'Processing failed'):job.state==='review_required'?'Ready for your review':job.state==='completed'?'Completed successfully':'Result expired'}</span>{job.state==='processing'&&<progress max="100" value={job.progress}/>}</div>{job.attempt>1&&job.state!=='completed'&&<span className="retry-label">Retry {job.attempt}/{job.maxAttempts}</span>}{job.state==='queued'&&<button className="button secondary" onClick={()=>api.cancelJob(job.id).then(()=>setRetry(v=>v+1))}>Cancel</button>}<span className={`job-state ${job.state}`}>{job.state.replace('_',' ')}</span></div>)}</section>}
    <div className="dashboard-columns"><section className="card panel"><div className="panel-head"><div><p className="eyebrow">Get started</p><h3>Set up your workspace</h3></div>{data && <span>{data.onboarding.filter(s=>s.complete).length} of {data.onboarding.length}</span>}</div><div className="steps">{(data?.onboarding ?? []).map((step,index) => <div className="step" key={step.id}><span className={step.complete ? 'step-check complete' : 'step-check'}>{step.complete ? <Check size={15}/> : index+1}</span><div><strong>{step.title}</strong><p>{step.description}</p></div><button aria-label={`Open ${step.title}`}><ChevronRight size={18}/></button></div>)}{!data && <div className="inline-loading"><span className="spinner"/> Loading steps…</div>}</div></section>
      <section className="card panel documents"><div className="panel-head"><div><p className="eyebrow">Your work</p><h3>Recent documents</h3></div><Link to="/app/documents">View all</Link></div>{data?.documents.length === 0 ? <div className="small-empty"><FileText/><p>No documents yet.</p><Link to="/app/rewrite">Start writing</Link></div> : <div className="document-list">{data?.documents.slice(0,4).map(doc => <Link to={`/app/documents`} className="document-row" key={doc.id}><span className="file-icon"><FileText size={18}/></span><div><strong>{doc.title}</strong><span><Clock3 size={12}/> {new Date(doc.updatedAt).toLocaleDateString()} · {doc.wordCount.toLocaleString()} words</span></div><span className="status">{doc.status}</span><ChevronRight size={17}/></Link>) ?? <div className="inline-loading"><span className="spinner"/> Loading documents…</div>}</div>}</section>
    </div>
    <section className="account-grid"><article className="card account-card"><div className="avatar large">AM</div><div><p className="eyebrow">Account</p><h3>Alex Morgan</h3><span>alex@example.com</span></div><Link to="/app/settings" className="button secondary">Manage</Link></article><article className="card plan-card"><div><p className="eyebrow">Current plan</p><h3>{data?.plan.name ?? '—'}</h3><span>{data?.plan.renewsAt ? `Renews ${new Date(data.plan.renewsAt).toLocaleDateString()}` : 'Plan details unavailable'}</span></div><div><strong>{data?.plan.price ?? '—'}</strong><Link to="/app/billing">Manage plan <ArrowRight size={14}/></Link></div></article></section>
  </div>
}
