import { useState, type ReactNode } from "react";
import { api } from "../lib/api";
import { AlertCircle, Check, ChevronRight, Download, LoaderCircle, RefreshCw, UploadCloud } from "lucide-react";

type Phase = "idle" | "loading" | "success" | "error";
type Result = Record<string, unknown>;
const message = (value: unknown) => typeof value === "string" ? value : JSON.stringify(value, null, 2);

function Operation({ phase, error, onRetry, children }: { phase: Phase; error?: string; onRetry?: () => void; children?: ReactNode }) {
  if (phase === "loading") return <div className="operation-state"><LoaderCircle className="spin"/><strong>Processing…</strong><span>Please keep this page open.</span><progress aria-label="Operation progress" /></div>;
  if (phase === "error") return <div className="operation-state danger"><AlertCircle/><strong>Operation failed</strong><span>{error}</span>{onRetry && <button className="button secondary" onClick={onRetry}><RefreshCw size={14}/>Retry</button>}</div>;
  if (phase === "success") return <div className="operation-state success"><Check/><strong>Complete</strong>{children}</div>;
  return null;
}

const steps = ["Upload", "Select ranges", "Configure", "Rewrite", "Review", "Download"];
export function RewriteStudio() {
  const [tab, setTab] = useState<"document"|"text"|"detect"|"format">("document");
  const [step, setStep] = useState(0); const [phase,setPhase]=useState<Phase>("idle");
  const [error,setError]=useState(""); const [result,setResult]=useState<Result>({}); const [file,setFile]=useState<File>();
  const [jobId,setJobId]=useState(""); const [text,setText]=useState(""); const [profile,setProfile]=useState("balanced"); const [intensity,setIntensity]=useState(.55);
  const [rangeMode,setRangeMode]=useState("automatic"); const [start,setStart]=useState(0); const [end,setEnd]=useState(10); const [terms,setTerms]=useState("");
  const [cycles,setCycles]=useState(1); const [edited,setEdited]=useState(""); const [formatJob,setFormatJob]=useState("");
  const run = async (task:()=>Promise<Result>, next?:number) => { setPhase("loading"); setError(""); try { const data=await task(); setResult(data); const id=String(data.job_id ?? data.jobId ?? data.id ?? ""); if(id)setJobId(id); setPhase("success"); if(next!==undefined)setStep(next); } catch(e){setError(e instanceof Error?e.message:"Unexpected error");setPhase("error");} };
  const requireFile = () => { if(!file){setError("Choose a supported file first.");setPhase("error");return false} return true };
  const upload=()=>requireFile()&&run(()=>api.uploadDocument(file!),1);
  const select=()=>run(()=>api.extractRanges(jobId,{selection_mode:rangeMode,start_order:start,end_order:end,selected_blocks:rangeMode==="manual"?text.split(",").filter(Boolean):undefined,visual_ranges:rangeMode==="visual"?[{start,end}]:undefined,turnitin_ranges:rangeMode==="turnitin"?text:undefined,include_headings:true}),2);
  const rewrite=async()=>{ await run(()=>api.rewriteDocument(jobId,{profile, intensity, protected_terms:terms.split("\n").filter(Boolean)}),4); for(let i=1;i<cycles;i++) await run(()=>api.rewriteDocument(jobId,{profile,intensity},true),4); };
  const validate=()=>run(()=>api.validateDocument(jobId,{text:edited||undefined}),5);
  const tabs = [{id:"document",label:"DOCX rewrite"},{id:"text",label:"Paste text"},{id:"detect",label:"AI detection"},{id:"format",label:"Formatting"}] as const;
  return <section className="studio">
    <header className="studio-head"><div><p className="eyebrow">Writing workspace</p><h2>Document studio</h2><p>Rewrite, inspect, validate and export without losing your formatting.</p></div></header>
    <div className="studio-tabs" role="tablist">{tabs.map(t=><button role="tab" aria-selected={tab===t.id} onClick={()=>{setTab(t.id);setPhase("idle")}} key={t.id}>{t.label}</button>)}</div>
    {tab==="document" && <div className="studio-layout"><nav className="stepper" aria-label="Rewrite progress">{steps.map((s,i)=><button key={s} className={i===step?"active":i<step?"done":""} onClick={()=>jobId||i===0?setStep(i):undefined}><span>{i<step?<Check size={13}/>:i+1}</span>{s}</button>)}</nav><div className="workspace-card card">
      {step===0&&<><Heading n="01" title="Upload a DOCX" copy="Your original remains untouched. Files are processed through the secure document gateway."/><FilePicker accept=".docx" file={file} onChange={setFile}/><button className="button primary" disabled={!file||phase==="loading"} onClick={upload}><UploadCloud size={16}/>Upload and inspect</button></>}
      {step===1&&<><Heading n="02" title="Choose what to rewrite" copy="Select content automatically, by block, visually, or from a Turnitin range report."/><div className="choice-grid">{["automatic","manual","visual","turnitin"].map(x=><button className={rangeMode===x?"selected":""} onClick={()=>setRangeMode(x)} key={x}><strong>{x}</strong><span>{x==="automatic"?"Detect body content":x==="manual"?"Enter block IDs":x==="visual"?"Use order boundaries":"Paste flagged ranges"}</span></button>)}</div>{rangeMode!=="automatic"&&<label className="field"><span>{rangeMode==="turnitin"?"Turnitin ranges":"Block IDs / notes"}</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder={rangeMode==="turnitin"?"Pages 2–4, similarity 18%":"p-12,p-13"}/></label>}{rangeMode==="visual"&&<div className="field-row"><label className="field"><span>Start order</span><input type="number" value={start} min={0} onChange={e=>setStart(+e.target.value)}/></label><label className="field"><span>End order</span><input type="number" value={end} min={start+1} onChange={e=>setEnd(+e.target.value)}/></label></div>}<button className="button primary" onClick={select}>Extract selection<ChevronRight size={16}/></button></>}
      {step===2&&<><Heading n="03" title="Configure extraction" copy="Protect names, citations, terminology and phrases from modification."/><label className="field"><span>Protected terms · one per line</span><textarea value={terms} onChange={e=>setTerms(e.target.value)} placeholder="AIREM\nSmith et al. (2024)"/></label><div className="check-list"><label><input type="checkbox" defaultChecked/> Preserve headings and captions</label><label><input type="checkbox" defaultChecked/> Preserve citations and references</label><label><input type="checkbox"/> Include table headers</label></div><button className="button primary" onClick={()=>setStep(3)}>Continue<ChevronRight size={16}/></button></>}
      {step===3&&<><Heading n="04" title="Rewrite controls" copy="Choose a profile, tune the strength and request additional refinement cycles."/><div className="field-row"><label className="field"><span>Rewrite profile</span><select value={profile} onChange={e=>setProfile(e.target.value)}><option value="balanced">Balanced academic</option><option value="natural">Natural</option><option value="formal">Formal</option><option value="manual">Manual controls</option></select></label><label className="field"><span>Additional cycles</span><input type="number" min="1" max="5" value={cycles} onChange={e=>setCycles(+e.target.value)}/></label></div><label className="field"><span>Rewrite intensity · {Math.round(intensity*100)}%</span><input type="range" min="0" max="1" step=".05" value={intensity} onChange={e=>setIntensity(+e.target.value)}/></label>{profile==="manual"&&<div className="check-list"><label><input type="checkbox" defaultChecked/> Vary sentence openings</label><label><input type="checkbox"/> Prefer concise vocabulary</label></div>}<button className="button primary" onClick={rewrite}>Start rewrite<ChevronRight size={16}/></button></>}
      {step===4&&<><Heading n="05" title="Review & diagnostics" copy="Compare source and rewritten text, edit the result, then run structural validation."/><div className="comparison"><label className="field"><span>Original</span><textarea readOnly value={String(result.original_text??"Original text will appear after processing.")}/></label><label className="field"><span>Rewritten</span><textarea value={edited||String(result.rewritten_text??result.text??"")} onChange={e=>setEdited(e.target.value)} placeholder="Rewritten text"/></label></div><div className="diagnostics"><span><Check size={14}/> Paragraph mapping</span><span><Check size={14}/> Protected terms</span><span><Check size={14}/> Formatting structure</span></div><button className="button primary" onClick={validate}>Validate and continue</button></>}
      {step===5&&<><Heading n="06" title="Reinsert & download" copy="Merge approved text into a copy of your original DOCX."/><button className="button secondary" onClick={()=>run(()=>api.reinsertDocument(jobId,{text:edited||undefined}))}>Reinsert into DOCX</button>{jobId?<a className="button primary" href={api.downloadUrl(jobId,"rewritten.docx")}><Download size={16}/>Download final DOCX</a>:<p className="empty-inline">Complete the earlier steps to create a download.</p>}</>}
      <Operation phase={phase} error={error} onRetry={()=>setPhase("idle")}>{Object.keys(result).length>0&&<details><summary>Operation details</summary><pre>{message(result)}</pre></details>}</Operation>
    </div></div>}
    {tab==="text"&&<Tool title="Rewrite pasted text" description="Rewrite short-form content without uploading a document."><label className="field"><span>Text</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste at least one sentence…"/></label><div className="field-row"><label className="field"><span>Profile</span><select value={profile} onChange={e=>setProfile(e.target.value)}><option>balanced</option><option>natural</option><option>formal</option></select></label><label className="field"><span>Intensity · {Math.round(intensity*100)}%</span><input type="range" min="0" max="1" step=".05" value={intensity} onChange={e=>setIntensity(+e.target.value)}/></label></div><button className="button primary" disabled={!text.trim()} onClick={()=>run(()=>api.rewriteText({text,profile,intensity}))}>Rewrite text</button><Operation phase={phase} error={error} onRetry={()=>run(()=>api.rewriteText({text,profile,intensity}))}>{<pre>{message(result)}</pre>}</Operation></Tool>}
    {tab==="detect"&&<Tool title="AI-content detection" description="Analyse pasted text or a DOCX/TXT file and review confidence signals."><label className="field"><span>Text to analyse</span><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Paste text…"/></label><FilePicker accept=".docx,.txt" file={file} onChange={setFile}/><div className="button-row"><button className="button primary" disabled={!text.trim()} onClick={()=>run(()=>api.detectText(text))}>Detect text</button><button className="button secondary" disabled={!file} onClick={()=>file&&run(()=>api.detectFile(file))}>Detect file</button></div><Operation phase={phase} error={error} onRetry={()=>setPhase("idle")}><pre>{message(result)}</pre></Operation></Tool>}
    {tab==="format"&&<Tool title="Formatting workspace" description="Analyse styles, preview recommended changes, configure rules and export a clean DOCX."><FilePicker accept=".docx" file={file} onChange={setFile}/><button className="button primary" disabled={!file} onClick={()=>file&&run(async()=>{const r=await api.analyseFormatting(file);setFormatJob(String(r.job_id??r.id??""));return r})}>Analyse formatting</button><div className="format-preview"><div><strong>Document preview</strong><h3>1. Introduction</h3><p>Style findings and a live structural preview appear here after analysis.</p></div><div className="check-list"><label><input type="checkbox" defaultChecked/> Normalise heading hierarchy</label><label><input type="checkbox" defaultChecked/> Standardise body spacing</label><label><input type="checkbox"/> Add page numbers</label></div></div><button className="button secondary" disabled={!formatJob} onClick={()=>run(()=>api.applyFormatting(formatJob,{normalise_headings:true,body_spacing:1.5,page_numbers:false}))}>Apply configuration</button>{formatJob&&<a className="button primary" href={api.downloadUrl(formatJob,"formatted.docx")}><Download size={16}/>Export DOCX</a>}<Operation phase={phase} error={error} onRetry={()=>setPhase("idle")}><pre>{message(result)}</pre></Operation></Tool>}
  </section>
}
function Heading({n,title,copy}:{n:string,title:string,copy:string}){return <div className="workspace-heading"><span>{n}</span><div><h3>{title}</h3><p>{copy}</p></div></div>}
function Tool({title,description,children}:{title:string,description:string,children:ReactNode}){return <div className="tool-card card"><h3>{title}</h3><p>{description}</p>{children}</div>}
function FilePicker({accept,file,onChange}:{accept:string,file?:File,onChange:(f:File)=>void}){return <label className="dropzone"><input type="file" accept={accept} onChange={e=>e.target.files?.[0]&&onChange(e.target.files[0])}/><UploadCloud/><strong>{file?file.name:"Choose a file or drop it here"}</strong><span>{accept.replaceAll(",",", ")} · maximum size is enforced by the gateway</span></label>}
