import { useState } from "react";
import { FileSearch, RefreshCw, ScanSearch } from "lucide-react";
import { api } from "../../lib/api";

type RecordValue = Record<string, unknown>;
const asRecord = (value: unknown): RecordValue | undefined => value && typeof value === "object" && !Array.isArray(value) ? value as RecordValue : undefined;
const number = (value: unknown) => typeof value === "number" && Number.isFinite(value) ? value : undefined;
const string = (value: unknown) => typeof value === "string" ? value : undefined;

function Report({ report, filename }: { report?: RecordValue; filename?: string }) {
  if (!report) return <div className="secondary-empty">Run a text or file analysis to see the v21 diagnostic report.</div>;
  const score = number(report.score) ?? 0; const dimensions = asRecord(report.dimensions) ?? {};
  const passages = Array.isArray(report.highest_risk_passages) ? report.highest_risk_passages.map(asRecord).filter(Boolean) as RecordValue[] : [];
  return <div className="detection-report" data-testid="detection-report">
    <section className="detection-summary"><div className="detection-ring" style={{ ["--risk" as string]: `${Math.max(0, Math.min(100, score))}%` }}><div><strong>{score.toFixed(1)}</strong><span>pattern score</span></div></div><div><p className="eyebrow">{filename ? `File · ${filename}` : "Diagnostic result"}</p><h3>{string(report.classification) ?? "Unclassified"}</h3><p>{string(report.disclaimer) ?? "Experimental writing-pattern diagnostic only."}</p><div className="detection-meta"><span><small>Confidence / sample adequacy</small><strong>{number(report.confidence)?.toFixed(0) ?? "—"}%</strong></span><span><small>Words</small><strong>{number(report.word_count)?.toLocaleString() ?? "—"}</strong></span><span><small>Sentences</small><strong>{number(report.sentence_count)?.toLocaleString() ?? "—"}</strong></span></div></div></section>
    <section className="secondary-panel"><div className="workspace-section-head"><div><p className="eyebrow">Detection components</p><h4>Pattern dimensions</h4></div></div><div className="detection-dimensions">{Object.entries(dimensions).map(([key, value]) => { const n = number(value) ?? 0; return <article key={key}><div><span>{key.replaceAll("_", " ")}</span><strong>{n.toFixed(1)}</strong></div><div className="secondary-score-track"><span style={{ width: `${Math.max(0, Math.min(100, n))}%` }}/></div></article>; })}</div></section>
    <section className="secondary-panel"><div className="workspace-section-head"><div><p className="eyebrow">Highest-risk passages</p><h4>Passage-level signals</h4></div><span>{passages.length} passage(s)</span></div>{passages.length ? <div className="risk-passage-list" data-testid="risk-passages">{passages.map((passage, index) => { const top = asRecord(passage.top_signal); return <article key={index}><div><strong>{string(passage.location) ?? `Passage ${number(passage.passage_number) ?? index + 1}`}</strong><span>{number(passage.score)?.toFixed(1) ?? "—"}</span></div><small>{number(passage.word_count)?.toLocaleString() ?? "—"} words{top ? ` · Main signal: ${string(top.label) ?? string(top.name) ?? "—"}` : ""}</small><p>{string(passage.preview) ?? ""}</p></article>; })}</div> : <div className="secondary-empty">No passage-level risk segments were returned for this sample.</div>}</section>
  </div>;
}

export function DetectionStudio() {
  const [mode, setMode] = useState<"text" | "file">("text"); const [text, setText] = useState(""); const [file, setFile] = useState<File>();
  const [report, setReport] = useState<RecordValue>(); const [filename, setFilename] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const runText = async () => { if (!text.trim()) return; setBusy(true); setError(""); try { const result = await api.detectText(text); setReport(result.report); setFilename(""); } catch (value) { setError(value instanceof Error ? value.message : "Detection failed."); } finally { setBusy(false); } };
  const runFile = async () => { if (!file) return; setBusy(true); setError(""); try { const result = await api.detectFile(file); setReport(result.report); setFilename(result.filename); } catch (value) { setError(value instanceof Error ? value.message : "Detection failed."); } finally { setBusy(false); } };
  return <div className="secondary-studio" data-testid="detection-studio"><section className="secondary-intro"><div><p className="eyebrow">Detection Studio</p><h3>Analyse text or DOCX/TXT without rewriting it</h3><p>This reproduces the v21 diagnostic view, including component scores and the highest-risk passages returned by the detector.</p></div></section><section className="secondary-panel"><div className="secondary-tab-row"><button className={mode === "text" ? "active" : ""} onClick={() => setMode("text")}>Paste text</button><button className={mode === "file" ? "active" : ""} onClick={() => setMode("file")}>Upload file</button></div><div className="secondary-notice"><strong>Important:</strong> this is an experimental writing-pattern diagnostic. It does not prove authorship and cannot guarantee the result of an external detector.</div>{mode === "text" ? <><label className="secondary-large-field"><span>Text to analyse</span><textarea aria-label="Detection text" value={text} onChange={e => setText(e.target.value)} placeholder="Paste text to analyse…"/></label><button className="button primary" disabled={busy || !text.trim()} onClick={runText}>{busy ? <RefreshCw className="spin" size={15}/> : <ScanSearch size={15}/>}Analyse text</button></> : <><label className="secondary-file-field"><input aria-label="Detection file" type="file" accept=".docx,.txt" onChange={e => setFile(e.target.files?.[0])}/><FileSearch/><strong>{file?.name ?? "Choose a DOCX or TXT file"}</strong></label><button className="button primary" disabled={busy || !file} onClick={runFile}>{busy ? <RefreshCw className="spin" size={15}/> : <FileSearch size={15}/>}Analyse file</button></>}{error && <div className="workspace-message error" role="alert">{error}</div>}</section><Report report={report} filename={filename}/></div>;
}
