import { useMemo, useState } from "react";
import type { DocumentBlock, DocumentInventory, FormattingSettingValue } from "@airem/contracts";
import { Download, FileCheck2, RefreshCw, UploadCloud } from "lucide-react";
import { api } from "../../lib/api";

type RecordValue = Record<string, unknown>;
type Settings = Record<string, FormattingSettingValue>;
const asRecord = (value: unknown): RecordValue | undefined => value && typeof value === "object" && !Array.isArray(value) ? value as RecordValue : undefined;
const num = (value: unknown, fallback: number) => typeof value === "number" && Number.isFinite(value) ? value : fallback;
const str = (value: unknown, fallback = "") => typeof value === "string" ? value : fallback;
const bool = (value: unknown) => value === true;
const styleSnapshot = (analysis: RecordValue, name: string) => asRecord(asRecord(analysis.styles)?.[name]);

function defaults(analysis: RecordValue): Settings {
  const normal = styleSnapshot(analysis, "Normal") ?? {}; const title = styleSnapshot(analysis, "Title") ?? {};
  const h1 = styleSnapshot(analysis, "Heading 1") ?? {}; const h2 = styleSnapshot(analysis, "Heading 2") ?? {}; const h3 = styleSnapshot(analysis, "Heading 3") ?? {}; const caption = styleSnapshot(analysis, "Caption") ?? {};
  const topFonts = Array.isArray(analysis.top_fonts) ? analysis.top_fonts : []; const topSizes = Array.isArray(analysis.top_sizes) ? analysis.top_sizes : [];
  const firstFont = Array.isArray(topFonts[0]) ? str(topFonts[0][0], "Arial") : "Arial"; const firstSize = Array.isArray(topSizes[0]) ? num(topSizes[0][0], 11) : 11;
  const sections = Array.isArray(analysis.sections) ? analysis.sections : []; const sec = asRecord(sections[0]) ?? {};
  return {
    body_font: str(normal.name, firstFont), body_size: num(normal.size_pt, firstSize), body_color: `#${str(normal.color, "000000")}`,
    heading_font: str(h1.name, str(normal.name, firstFont)), heading_color: `#${str(h1.color, "1F4E79")}`,
    title_size: num(title.size_pt, 22), h1_size: num(h1.size_pt, 16), h2_size: num(h2.size_pt, 14), h3_size: num(h3.size_pt, 12),
    caption_font: str(caption.name, str(normal.name, firstFont)), caption_size: num(caption.size_pt, 10), caption_color: `#${str(caption.color, "404040")}`,
    line_spacing: 1.15, space_after: 6,
    page_size: num(sec.width_inches, 8.27) >= 8.4 ? "letter" : "a4", orientation: str(sec.orientation, "portrait"),
    margin_top: num(sec.top_margin, 1), margin_bottom: num(sec.bottom_margin, 1), margin_left: num(sec.left_margin, 1), margin_right: num(sec.right_margin, 1),
    header_text: "", footer_text: "", page_border_color: "#808080", page_border_size: 8, page_border: false, different_first_page: false,
    table_font: str(normal.name, firstFont), table_size: 10, table_style: "Table Grid", table_border_color: "#808080", table_border_size: 4,
    repeat_header: true, bold_table_header: true, convert_captions: true, page_numbers: true, add_toc: false, add_lof: false, add_lot: false,
  };
}

function TextControl({ settings, set, id, label, type = "text", min, max, step }: { settings: Settings; set: (id: string, value: FormattingSettingValue) => void; id: string; label: string; type?: string; min?: number; max?: number; step?: number }) {
  return <label className="format-control"><span>{label}</span><input aria-label={label} type={type} min={min} max={max} step={step} value={String(settings[id] ?? "")} onChange={e => set(id, type === "number" ? Number(e.target.value) : e.target.value)}/></label>;
}
function SelectControl({ settings, set, id, label, children }: { settings: Settings; set: (id: string, value: FormattingSettingValue) => void; id: string; label: string; children: React.ReactNode }) {
  return <label className="format-control"><span>{label}</span><select aria-label={label} value={String(settings[id] ?? "")} onChange={e => set(id, e.target.value)}>{children}</select></label>;
}
function Check({ settings, set, id, label }: { settings: Settings; set: (id: string, value: FormattingSettingValue) => void; id: string; label: string }) {
  return <label className="format-check"><input type="checkbox" checked={bool(settings[id])} onChange={e => set(id, e.target.checked)}/><span>{label}</span></label>;
}

function PreviewRuns({ block, settings }: { block: Extract<DocumentBlock, { type: "paragraph" }>; settings: Settings }) {
  const style = block.style.toLowerCase(); const heading = style.startsWith("heading"); const title = style === "title"; const caption = block.is_caption || style === "caption";
  const font = caption ? settings.caption_font : heading ? settings.heading_font : settings.body_font;
  const size = title ? settings.title_size : style.startsWith("heading 1") ? settings.h1_size : style.startsWith("heading 2") ? settings.h2_size : style.startsWith("heading 3") ? settings.h3_size : caption ? settings.caption_size : settings.body_size;
  const color = caption ? settings.caption_color : heading || title ? settings.heading_color : settings.body_color;
  return <p className={`format-preview-paragraph ${heading || title ? "heading" : ""}`} style={{ textAlign: block.visual.alignment, marginLeft: `${block.visual.left_indent_pt}px`, textIndent: `${block.visual.first_line_indent_pt}px`, fontFamily: String(font), fontSize: `${size}pt`, color: String(color), fontWeight: heading || title ? 700 : undefined, lineHeight: String(settings.line_spacing), marginBottom: `${settings.space_after}pt` }}>{block.visual.list_item && <span className="format-list-prefix">•</span>}{block.visual.runs.map((run, index) => <span key={index} style={{ fontStyle: run.italic ? "italic" : undefined, textDecoration: run.underline ? "underline" : undefined, fontWeight: heading || title ? 700 : run.bold ? 700 : undefined }}>{run.text}</span>)}{caption && bool(settings.convert_captions) && <em className="format-field-badge">SEQ</em>}</p>;
}

function LivePreview({ inventory, settings }: { inventory: DocumentInventory; settings: Settings }) {
  const letter = settings.page_size === "letter"; const landscape = settings.orientation === "landscape";
  const w = letter ? 612 : 595.4; const h = letter ? 792 : 841.7; const width = landscape ? h : w; const height = landscape ? w : h;
  const margin = { top: Number(settings.margin_top) * 72, bottom: Number(settings.margin_bottom) * 72, left: Number(settings.margin_left) * 72, right: Number(settings.margin_right) * 72 };
  return <div className="format-preview-shell"><div className="format-preview-toolbar"><strong>Live Word-style preview</strong><span>{String(settings.page_size).toUpperCase()} · {String(settings.orientation)}</span></div><div className="format-preview-scroll"><div data-testid="format-live-preview" className="format-word-page" style={{ width, minHeight: height, padding: `${margin.top}px ${margin.right}px ${margin.bottom}px ${margin.left}px`, outline: bool(settings.page_border) ? `${Math.max(1, Number(settings.page_border_size) / 2)}px solid ${String(settings.page_border_color)}` : undefined, outlineOffset: bool(settings.page_border) ? "-8px" : undefined }}>
    {String(settings.header_text).trim() && <div className="format-header">{String(settings.header_text)}</div>}
    {(bool(settings.add_toc) || bool(settings.add_lof) || bool(settings.add_lot)) && <div className="format-front-fields">{bool(settings.add_toc) && <div><strong>Table of Contents</strong><span>Word field inserted on export</span></div>}{bool(settings.add_lof) && <div><strong>List of Figures</strong><span>Word field inserted on export</span></div>}{bool(settings.add_lot) && <div><strong>List of Tables</strong><span>Word field inserted on export</span></div>}</div>}
    {inventory.blocks.map(block => block.type === "paragraph" ? <PreviewRuns key={block.block_id} block={block} settings={settings}/> : <table className={`format-preview-table ${settings.table_style === "Light Shading Accent 1" ? "shaded" : settings.table_style === "Light Grid Accent 1" ? "light-grid" : ""}`} key={block.block_id} style={{ fontFamily: String(settings.table_font), fontSize: `${settings.table_size}pt`, borderColor: String(settings.table_border_color) }}><tbody>{block.rendered_rows.map(row => <tr key={row.row_index}>{row.cells.map(cell => <td key={cell.column_index} style={{ borderColor: String(settings.table_border_color), borderWidth: Math.max(1, Number(settings.table_border_size) / 4), fontWeight: row.row_index === 0 && bool(settings.bold_table_header) ? 700 : undefined }}>{cell.paragraphs.map(p => <p key={p.visual_id}>{p.text}</p>)}{row.row_index === 0 && bool(settings.repeat_header) && <em className="format-field-badge">repeat</em>}</td>)}</tr>)}</tbody></table>)}
    {(String(settings.footer_text).trim() || bool(settings.page_numbers)) && <div className="format-footer">{String(settings.footer_text)}{bool(settings.page_numbers) && <span> Page 1</span>}</div>}
  </div></div></div>;
}

export function FormattingStudio() {
  const [file, setFile] = useState<File>(); const [jobId, setJobId] = useState(""); const [analysis, setAnalysis] = useState<RecordValue>(); const [inventory, setInventory] = useState<DocumentInventory>();
  const [settings, setSettings] = useState<Settings>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [downloadUrl, setDownloadUrl] = useState(""); const [reportUrl, setReportUrl] = useState(""); const [result, setResult] = useState<RecordValue>();
  const summary = useMemo(() => analysis ? { paragraphs: num(analysis.paragraph_count, 0), tables: num(analysis.table_count, 0), sections: num(analysis.section_count, 0), captions: num(analysis.manual_caption_count, 0) } : undefined, [analysis]);
  const set = (id: string, value: FormattingSettingValue) => { setSettings(current => ({ ...current, [id]: value })); setDownloadUrl(""); setResult(undefined); };
  const analyse = async () => { if (!file) return; setBusy(true); setError(""); try { const response = await api.analyseFormatting(file); setJobId(response.job_id); setAnalysis(response.analysis); setInventory(response.preview as unknown as DocumentInventory); setSettings(defaults(response.analysis)); setDownloadUrl(""); setReportUrl(""); } catch (value) { setError(value instanceof Error ? value.message : "Formatting analysis failed."); } finally { setBusy(false); } };
  const apply = async () => { if (!jobId) return; setBusy(true); setError(""); try { const response = await api.applyFormatting(jobId, settings); setResult(response.result); setDownloadUrl(response.download_url); setReportUrl(response.report_url); } catch (value) { setError(value instanceof Error ? value.message : "Formatting failed."); } finally { setBusy(false); } };
  return <div className="secondary-studio formatting-studio" data-testid="formatting-studio"><section className="secondary-intro"><div><p className="eyebrow">Formatting & Caption Studio</p><h3>Analyse, preview and export Word formatting</h3><p>The live preview applies the same v21 typography, page, table, caption and Word-field controls used by the final DOCX formatter.</p></div></section>
    {!analysis && <section className="secondary-panel"><label className="secondary-file-field"><input aria-label="Formatting DOCX" type="file" accept=".docx" onChange={e => setFile(e.target.files?.[0])}/><UploadCloud/><strong>{file?.name ?? "Choose a DOCX"}</strong></label><button className="button primary" disabled={!file || busy} onClick={analyse}>{busy ? <RefreshCw className="spin" size={15}/> : <FileCheck2 size={15}/>}Analyse formatting</button>{error && <div className="workspace-message error" role="alert">{error}</div>}</section>}
    {analysis && inventory && <div className="formatting-layout"><div className="formatting-controls"><section className="secondary-panel"><div className="workspace-section-head"><div><p className="eyebrow">Detected document</p><h4>{file?.name}</h4></div><button className="button secondary" onClick={() => { setAnalysis(undefined); setInventory(undefined); setJobId(""); }}>Analyse another</button></div><div className="format-summary-pills"><span>{summary?.paragraphs} paragraphs</span><span>{summary?.tables} tables</span><span>{summary?.sections} sections</span><span>{summary?.captions} manual captions</span></div></section>
      <section className="secondary-panel"><h4>Typography and styles</h4><div className="format-control-grid"><TextControl settings={settings} set={set} id="body_font" label="Body font"/><TextControl settings={settings} set={set} id="body_size" label="Body size" type="number" min={6} max={40} step={0.5}/><TextControl settings={settings} set={set} id="body_color" label="Body colour" type="color"/><TextControl settings={settings} set={set} id="heading_font" label="Heading font"/><TextControl settings={settings} set={set} id="heading_color" label="Heading colour" type="color"/><TextControl settings={settings} set={set} id="title_size" label="Title size" type="number" min={8} max={72} step={0.5}/><TextControl settings={settings} set={set} id="h1_size" label="Heading 1 size" type="number" min={8} max={54} step={0.5}/><TextControl settings={settings} set={set} id="h2_size" label="Heading 2 size" type="number" min={8} max={48} step={0.5}/><TextControl settings={settings} set={set} id="h3_size" label="Heading 3 size" type="number" min={8} max={42} step={0.5}/><TextControl settings={settings} set={set} id="caption_font" label="Caption font"/><TextControl settings={settings} set={set} id="caption_size" label="Caption size" type="number" min={6} max={30} step={0.5}/><TextControl settings={settings} set={set} id="caption_color" label="Caption colour" type="color"/><SelectControl settings={settings} set={set} id="line_spacing" label="Line spacing"><option value="1">Single</option><option value="1.15">1.15</option><option value="1.5">1.5</option><option value="2">Double</option></SelectControl><TextControl settings={settings} set={set} id="space_after" label="Space after paragraphs (pt)" type="number" min={0} max={72}/></div></section>
      <section className="secondary-panel"><h4>Page setup</h4><div className="format-control-grid"><SelectControl settings={settings} set={set} id="page_size" label="Page size"><option value="a4">A4</option><option value="letter">Letter</option></SelectControl><SelectControl settings={settings} set={set} id="orientation" label="Orientation"><option value="portrait">Portrait</option><option value="landscape">Landscape</option></SelectControl><TextControl settings={settings} set={set} id="margin_top" label="Top margin (inches)" type="number" min={0.2} max={3} step={0.1}/><TextControl settings={settings} set={set} id="margin_bottom" label="Bottom margin (inches)" type="number" min={0.2} max={3} step={0.1}/><TextControl settings={settings} set={set} id="margin_left" label="Left margin (inches)" type="number" min={0.2} max={3} step={0.1}/><TextControl settings={settings} set={set} id="margin_right" label="Right margin (inches)" type="number" min={0.2} max={3} step={0.1}/><TextControl settings={settings} set={set} id="header_text" label="Header text"/><TextControl settings={settings} set={set} id="footer_text" label="Footer text"/><TextControl settings={settings} set={set} id="page_border_color" label="Page border colour" type="color"/><TextControl settings={settings} set={set} id="page_border_size" label="Page border width" type="number" min={2} max={24}/></div><div className="format-check-grid"><Check settings={settings} set={set} id="page_border" label="Add page border"/><Check settings={settings} set={set} id="different_first_page" label="Different first-page header/footer"/></div></section>
      <section className="secondary-panel"><h4>Tables, captions and Word fields</h4><div className="format-control-grid"><TextControl settings={settings} set={set} id="table_font" label="Table font"/><TextControl settings={settings} set={set} id="table_size" label="Table size" type="number" min={6} max={30} step={0.5}/><SelectControl settings={settings} set={set} id="table_style" label="Table style"><option value="Table Grid">Table Grid</option><option value="Light Shading Accent 1">Light Shading Accent 1</option><option value="Light Grid Accent 1">Light Grid Accent 1</option></SelectControl><TextControl settings={settings} set={set} id="table_border_color" label="Table border colour" type="color"/><TextControl settings={settings} set={set} id="table_border_size" label="Table border width" type="number" min={2} max={24}/></div><div className="format-check-grid"><Check settings={settings} set={set} id="repeat_header" label="Repeat table header rows"/><Check settings={settings} set={set} id="bold_table_header" label="Bold table header rows"/><Check settings={settings} set={set} id="convert_captions" label="Convert captions to Word SEQ fields"/><Check settings={settings} set={set} id="page_numbers" label="Add page numbers"/><Check settings={settings} set={set} id="add_toc" label="Add Table of Contents"/><Check settings={settings} set={set} id="add_lof" label="Add List of Figures"/><Check settings={settings} set={set} id="add_lot" label="Add List of Tables"/></div></section>
      <section className="format-action-bar"><button className="button primary" disabled={busy} onClick={apply}>{busy ? <RefreshCw className="spin" size={15}/> : <FileCheck2 size={15}/>}Apply configuration</button>{downloadUrl && <a className="button primary" href={downloadUrl}><Download size={15}/>Export formatted DOCX</a>}</section>{error && <div className="workspace-message error" role="alert">{error}</div>}{result && <div className="workspace-message success" data-testid="formatting-result"><span><strong>Formatting complete.</strong> {num(result.sections_formatted, 0)} section(s) and {num(result.tables_formatted, 0)} table(s) processed.</span>{reportUrl && <a href={reportUrl}>Formatting report</a>}</div>}</div><LivePreview inventory={inventory} settings={settings}/></div>}
  </div>;
}
